-- ============================================
-- Seed data placeholder
-- ============================================
-- Add per-project test data here.
-- This file is run with `supabase db reset` during local development.
--
-- Example:
--   insert into public.profiles (id, email, full_name)
--   values ('00000000-0000-0000-0000-000000000001', 'test@example.com', 'Test User');
